#!/usr/bin/env bash
set -e
USER_INITIALS=$1
HOURS=$2

if [[ -z $USER_INITIALS ]]; then
  echo "Usage: vkl (user_initials|lastpass_email) [hours_to_login]"
  exit 1
fi

if [[ -z $HOURS ]]; then
  CURRENT_HOUR=`date +%H | sed 's/^0//'`
  HOURS=`expr 18 - $CURRENT_HOUR`
  echo "Hours: $HOURS"
fi

USER_PREFIX=$(grep $USER_INITIALS ~/.git-authors | awk -F '; ' '{print $2}')
if [[ $USER_PREFIX == "" ]]; then
  USER=$USER_INITIALS
  echo 'Unknown initial. Using as email'
else
  USER_DOMAIN=$(grep domain ~/.git-authors | awk -F ': ' '{print $2}')
  USER="$USER_PREFIX@$USER_DOMAIN"
fi

if [[ `lpass status` != *$USER* ]]; then
  lpass login $USER
fi

unset DISPLAY # forces ssh-add to ask for the password in the terminal

/usr/bin/ssh-add -D
lpass show --notes 'Productivity Tools/id_rsa' | /usr/bin/ssh-add -t ${HOURS}H -

exit 0
